### ISSUE TITLE
 Non-functional MRA 

### ISSUE THREAD

**Issue by kaloun34** [MiSTer-devel/Arcade-Druaga_MiSTer#20]
![20210610_155848-screen](https://user-images.githubusercontent.com/54940754/121538138-d492c300-ca04-11eb-8fcb-9be2dfa337c9.png)
Hello

MRA "Pac & Pal"  "Pac-Man & Chomp Chomp"  "Super Pac-Man" have display issues since this update

**Comment by tjanas** [comment]
@misteraddons can you reproduce this error after your recent change to the MRA?

**Comment by kaloun34** [comment]
Hello,
No, it's okay no more display problem
Thanks
