### ISSUE TITLE
Grobda Not Loading

### ISSUE THREAD

**Issue by misteraddons** [MiSTer-devel/Arcade-Druaga_MiSTer#23]
Issue occurs with both new MRA and previous MRA

**Comment by wwark** [comment]
On my side, it works with the last RBF (https://github.com/MiSTer-devel/Arcade-Druaga_MiSTer/blob/master/releases/Arcade-Druaga_20210610.rbf) and the previous and new MRA.
Do you have the loading bar or not on your side ? Or it is black screen after the loading bar ?

**Comment by misteraddons** [comment]
Works fine for me now. Thanks for checking :)
