### ISSUE TITLE
Mappy.mra is apparently broken XML

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/Arcade-Druaga_MiSTer#4]
**/media/fat/Scripts/mra_rom_check.sh** says:
```
There are issues with one or more of your MRA or MAME files

Please gently encourage Developers and Maintainers of MRA files to correct files with broken XML, missing CRC values and missing MAME versions values to correct their MRA files
```

**/tmp/mra_rom_check.log** says:
```
Broken XML:/media/fat/_Arcade/Mappy.mra
```

**Comment by c0d3h4x0r** [comment]
I'm guessing it might be due to the use of unencoded `/` and `&` characters inside the `category` field.

**Comment by MrX-8B** [comment]
There may be a problem with mra_rom_check.sh
I'll contact the person in charge.

**Comment by sorgelig** [comment]
the problem is in mra apparently as direct symbols / and & are prohibited in xml. They should be encoded. I suggest to replace / with , and & with "and", so it will be readable and conform the xml standard.

**Comment by MrX-8B** [comment]
On MiSTer, I was wondering if I didn't have to follow the standard, since I can load it on this MRA as well.
Then I'll follow your suggestion to modify it.

**Comment by MrX-8B** [comment]
Fixed three MRA files: Mappy, Druaga, and DigDug2.
Confirmed that mra_rom_check.sh does not give error messages.

**Comment by sorgelig** [comment]
Actually MiSTer's xml parser is simple and doesn't care of it. 
It's just about that checker which enforces this check.
