### ISSUE TITLE
Latest MRA changes have wrong CRCs or are ill-formed

### ISSUE THREAD

**Issue by theypsilon** [MiSTer-devel/Arcade-Druaga_MiSTer#8]
After this PR https://github.com/MiSTer-devel/Arcade-Druaga_MiSTer/pull/6 , there are the following errors:
![image](https://user-images.githubusercontent.com/852246/113930666-dd42ff00-97f1-11eb-81df-71e128ab380a.png)
`
Pac-Man & Chomp Chomp.mra` and `Pac & Pal.mra` are ill-formed (Probably the **&**, has to be `&amp;` to be a valid XML file).
`Super Pacman.mra` misses the CRCs.

**Comment by Missingno255** [comment]
After the update on April 9th, it still doesn't boot Pac & Pal and Pac-Man & Chomp Chomp, at least on my end. I don't know if anyone else is having the same issue though.
